SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.price) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.status = 'DONE'
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(UGB.price) >= 700000
ORDER BY SUM(UGB.price) ASC;